export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const POPULATE_FORM_FIELDS = 'POPULATE_FORM_FIELDS'
export const MANIPULATE_ORDER_ITEMS = 'MANIPULATE_ORDER_ITEMS'
